name: 🧪 Test GitHub Secrets

on:
  workflow_dispatch:  # allows you to trigger manually

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Check out repository
        uses: actions/checkout@v4

      - name: 🔍 Test environment variables
        run: |
          echo "OPENAI_API_KEY is set? ${{ secrets.OPENAI_API_KEY != '' }}"
          echo "BUILD_SECRET is set? ${{ secrets.BUILD_SECRET != '' }}"
          echo "GITHUB_TOKEN is set? ${{ secrets.GITHUB_TOKEN != '' }}"

      - name: 🧩 Verify OpenAI API connectivity (simple test)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          curl https://api.openai.com/v1/models \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -o /dev/null -w "%{http_code}\n" -s
